

CREATE TABLE CATEGORIES (
		CATEGORYID BIGINT NOT NULL,
		CATEGORYNAME VARCHAR(15) NOT NULL,
		DESCRIPTION VARCHAR(255)
	);

CREATE TABLE SUPPLIERS (
		SUPPLIERID BIGINT NOT NULL,
		COMPANYNAME VARCHAR(40) NOT NULL,
		CONTACTNAME VARCHAR(30)
	);

CREATE TABLE ORDERDETAILS (
		ORDERID BIGINT NOT NULL,
		PRODUCTID BIGINT NOT NULL,
		QUANTITY SMALLINT NOT NULL
	);

CREATE TABLE CUSTOMERS (
		CUSTOMERID CHAR(5) NOT NULL,
		COMPANYNAME VARCHAR(40) NOT NULL,
		CONTACTNAME VARCHAR(30),
		STREET VARCHAR(60),
		CITY VARCHAR(15),
		STATE VARCHAR(15)
	);

CREATE TABLE ORDERS (
		ORDERID BIGINT NOT NULL,
		CUSTOMERID CHAR(5),
		ORDERDATE DATE
	);

CREATE TABLE PRODUCTS (
		PRODUCTID BIGINT NOT NULL,
		PRODUCTNAME VARCHAR(40) NOT NULL,
		SUPPLIERID BIGINT,
		CATEGORYID BIGINT,
		UNITPRICE DECIMAL(7 , 2)
	);

CREATE INDEX SQL070509075952780 ON ORDERDETAILS (ORDERID ASC);

CREATE INDEX SQL070509075952680 ON PRODUCTS (SUPPLIERID ASC);

CREATE UNIQUE INDEX SQL070509075952170 ON ORDERDETAILS (ORDERID ASC, PRODUCTID ASC);

CREATE INDEX SQL070509075952850 ON ORDERDETAILS (PRODUCTID ASC);

CREATE INDEX SQL070509075952280 ON ORDERS (CUSTOMERID ASC);

CREATE UNIQUE INDEX SQL070509075951290 ON CUSTOMERS (CUSTOMERID ASC);

CREATE UNIQUE INDEX SQL070509075951920 ON ORDERS (ORDERID ASC);

CREATE UNIQUE INDEX SQL070509075952060 ON PRODUCTS (PRODUCTID ASC);

CREATE UNIQUE INDEX SQL070509075951590 ON SUPPLIERS (SUPPLIERID ASC);

CREATE INDEX SQL070509075952540 ON PRODUCTS (CATEGORYID ASC);

CREATE UNIQUE INDEX SQL070509075951750 ON CATEGORIES (CATEGORYID ASC);

ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORYID);

ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID);

ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID);

ALTER TABLE SUPPLIERS ADD CONSTRAINT PK_SUPPLIERS PRIMARY KEY (SUPPLIERID);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ORDERID);

ALTER TABLE ORDERDETAILS ADD CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (ORDERID, PRODUCTID);

ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDDET_PROD FOREIGN KEY (PRODUCTID)
	REFERENCES PRODUCTS (PRODUCTID);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_CUST FOREIGN KEY (CUSTOMERID)
	REFERENCES CUSTOMERS (CUSTOMERID);

ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDDET_ORD FOREIGN KEY (ORDERID)
	REFERENCES ORDERS (ORDERID);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORYID)
	REFERENCES CATEGORIES (CATEGORYID);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PROD_SUPP FOREIGN KEY (SUPPLIERID)
	REFERENCES SUPPLIERS (SUPPLIERID);

